# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Server installation style guide
subtitle: Ubuntu 18.04 + PHP7 + Apache
email: oom@oscarotero.com
description: >
  This is a style guide to install and configure web servers easily. You can use it with any VPS with root access. Feel free to contribute with whatever you want (comments, forks, stars, etc)
baseurl: "/server-style-guide"
url: "https://oscarotero.github.io"
twitter_username: misteroom
github_username:  oscarotero

# Build settings
markdown: kramdown
